### ISSUE TITLE
Unable to verify secret hash

### ISSUE THREAD

**Issue by marcschroeter** [aws-samples/amazon-cognito-passwordless-email-auth#10]
Hello,

we changed our cognito pool to support email or phonenumber as username, but now we get follwing error with the example app.

Thank you so much for your help!

<img width="441" alt="Screenshot 2019-04-17 at 10 51 33" src="https://user-images.githubusercontent.com/36969257/56274368-e4513e00-60fe-11e9-8951-34a3dad927e0.png">

<img width="1665" alt="Bildschirmfoto 2019-04-16 um 22 24 02" src="https://user-images.githubusercontent.com/36969257/56274517-22e6f880-60ff-11e9-8481-9d96ec6c92d6.png">

**Comment by ottokruse** [comment]
Hi. I think you’re using a User pool client with a secret? Try one without a client secret. Does that help?

**Comment by ottokruse** [comment]
Was this resolved? Can the issue be closed?
