### ISSUE TITLE
Passwordless authentication Android

### ISSUE THREAD

**Issue by MichalCR** [aws-samples/amazon-cognito-passwordless-email-auth#12]
Hi,

I'm trying to create passwordless email authentications on Android. I follow this example: https://aws.amazon.com/blogs/mobile/implementing-passwordless-email-authentication-with-amazon-cognito/. I was able to signup user however I struggle with signing in. In the above instruction, there is only JS client example and it contains methods what Android SDK does not have e.g. `Auth.signIn(email)` or `Auth.signIn(email)`. Can you please tell how can I make a passwordless authentication using Cognito Android SDK?

**Comment by ottokruse** [comment]
Hi there. Does the info on this page help you?: https://docs.aws.amazon.com/cognito/latest/developerguide/tutorial-integrating-user-pools-android.html#tutorial-integrating-user-pools-user-sign-in-android

**Comment by ottokruse** [comment]
Hi @MichalCR , did you get further?

**Comment by MichalCR** [comment]
Hi,

yes It turned you that Android SDK works a bit different than JS SDK but I was able to find a way to send requests that I was missing. THX!
