### ISSUE TITLE
npm install failed - cognito-email-auth-backend@1.0.0~postinstall: Failed to exec postinstall script

### ISSUE THREAD

**Issue by hanifasterling** [aws-samples/amazon-cognito-passwordless-email-auth#29]
**From the command prompt:**
npm WARN create-auth-challenge@1.0.0 No description
npm WARN create-auth-challenge@1.0.0 No repository field.

audited 1 package in 1.035s
found 0 vulnerabilities

The system cannot find the path specified.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cognito-email-auth-backend@1.0.0 postinstall: `cd ./lambda-triggers/create-auth-challenge && npm i && cd -`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cognito-email-auth-backend@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hanifa.amer\AppData\Roaming\npm-cache\_logs\2020-10-20T09_49_46_440Z-debug.log

**From the debug log:**

58 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 373ms
59 timing audit body Completed in 1ms
60 silly lifecycle cognito-email-auth-backend@1.0.0~postinstall: Returned: code: 1  signal: null
61 info lifecycle cognito-email-auth-backend@1.0.0~postinstall: Failed to exec postinstall script
62 verbose stack Error: cognito-email-auth-backend@1.0.0 postinstall: `cd ./lambda-triggers/create-auth-challenge && npm i && cd -`
62 verbose stack Exit status 1
62 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
62 verbose stack     at EventEmitter.emit (events.js:315:20)
62 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
62 verbose stack     at ChildProcess.emit (events.js:315:20)
62 verbose stack     at maybeClose (internal/child_process.js:1051:16)
62 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)

**Comment by hanifasterling** [comment]
`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v14.4.0
4 verbose npm-session edaa20384a04ed65
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall cognito-email-auth-backend@1.0.0
7 info lifecycle cognito-email-auth-backend@1.0.0~preinstall: cognito-email-auth-backend@1.0.0
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 timing stage:loadCurrentTree Completed in 82ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 33ms
16 silly install loadAllDepsIntoIdealTree
17 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 27ms
18 timing stage:loadIdealTree Completed in 68ms
19 silly currentTree cognito-email-auth-backend@1.0.0
19 silly currentTree +-- @types/aws-lambda@8.10.39
19 silly currentTree +-- @types/node@10.17.9
19 silly currentTree +-- aws-sdk@2.589.0
19 silly currentTree +-- base64-js@1.3.1
19 silly currentTree +-- buffer@4.9.1
19 silly currentTree +-- crypto-secure-random-digit@1.0.9
19 silly currentTree +-- events@1.1.1
19 silly currentTree +-- ieee754@1.1.13
19 silly currentTree +-- isarray@1.0.0
19 silly currentTree +-- jmespath@0.15.0
19 silly currentTree +-- punycode@1.3.2
19 silly currentTree +-- querystring@0.2.0
19 silly currentTree +-- sax@1.2.1
19 silly currentTree +-- typescript@3.7.3
19 silly currentTree +-- url@0.10.3
19 silly currentTree +-- uuid@3.3.2
19 silly currentTree +-- xml2js@0.4.19
19 silly currentTree `-- xmlbuilder@9.0.7
20 silly idealTree cognito-email-auth-backend@1.0.0
20 silly idealTree +-- @types/aws-lambda@8.10.39
20 silly idealTree +-- @types/node@10.17.9
20 silly idealTree +-- aws-sdk@2.589.0
20 silly idealTree +-- base64-js@1.3.1
20 silly idealTree +-- buffer@4.9.1
20 silly idealTree +-- crypto-secure-random-digit@1.0.9
20 silly idealTree +-- events@1.1.1
20 silly idealTree +-- ieee754@1.1.13
20 silly idealTree +-- isarray@1.0.0
20 silly idealTree +-- jmespath@0.15.0
20 silly idealTree +-- punycode@1.3.2
20 silly idealTree +-- querystring@0.2.0
20 silly idealTree +-- sax@1.2.1
20 silly idealTree +-- typescript@3.7.3
20 silly idealTree +-- url@0.10.3
20 silly idealTree +-- uuid@3.3.2
20 silly idealTree +-- xml2js@0.4.19
20 silly idealTree `-- xmlbuilder@9.0.7
21 silly install generateActionsToTake
22 timing stage:generateActionsToTake Completed in 6ms
23 silly diffTrees action count 0
24 silly decomposeActions action count 0
25 silly install executeActions
26 silly doSerial global-install 0
27 verbose correctMkdir C:\Users\UserPC\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
28 verbose makeCacheDir UID & GID are irrelevant on win32
29 verbose lock using C:\Users\UserPC\AppData\Roaming\npm-cache\_locks\staging-878871dc6903eb86.lock for C:\Users\UserPC\Documents\test-code\amazon-cognito-passwordless-email-auth\cognito\node_modules\.staging
30 silly doParallel extract 0
31 silly doReverseSerial unbuild 0
32 silly doSerial remove 0
33 silly doSerial move 0
34 silly doSerial finalize 0
35 silly doParallel refresh-package-json 0
36 silly doParallel preinstall 0
37 silly doSerial build 0
38 silly doSerial global-link 0
39 silly doParallel update-linked 0
40 silly doSerial install 0
41 silly doSerial postinstall 0
42 verbose unlock done using C:\Users\UserPC\AppData\Roaming\npm-cache\_locks\staging-878871dc6903eb86.lock for C:\Users\UserPC\Documents\test-code\amazon-cognito-passwordless-email-auth\cognito\node_modules\.staging
43 timing stage:executeActions Completed in 70ms
44 timing stage:rollbackFailedOptional Completed in 1ms
45 silly install runPostinstallTopLevelLifecycles
46 silly build cognito-email-auth-backend@1.0.0
47 info linkStuff cognito-email-auth-backend@1.0.0
48 silly linkStuff cognito-email-auth-backend@1.0.0 has C:\Users\UserPC\Documents\test-code\amazon-cognito-passwordless-email-auth as its parent node_modules
49 silly install cognito-email-auth-backend@1.0.0
50 info lifecycle cognito-email-auth-backend@1.0.0~install: cognito-email-auth-backend@1.0.0
51 silly postinstall cognito-email-auth-backend@1.0.0
52 info lifecycle cognito-email-auth-backend@1.0.0~postinstall: cognito-email-auth-backend@1.0.0
53 verbose lifecycle cognito-email-auth-backend@1.0.0~postinstall: unsafe-perm in lifecycle true
54 verbose lifecycle cognito-email-auth-backend@1.0.0~postinstall: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\UserPC\Documents\test-code\amazon-cognito-passwordless-email-auth\cognito\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\UserPC\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Google\Google Apps Migration\;C:\Program Files (x86)\Google\Google Apps Sync\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\ProgramData\chocolatey\bin;C:\Program Files\MongoDB\Server\4.2\bin;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\dotnet\;C:\Program Files (x86)\MSBuild\14.0\Bin;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\OpenJDK\jdk-14.0.1\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Symantec\VIP Access Client\;C:\Program Files\Amazon\AWSCLIV2\;C:\Program Files\Amazon\AWSSAMCLI\bin\;C:\Users\UserPC\AppData\Local\Programs\Python\Python38-32\Scripts\;C:\Users\UserPC\AppData\Local\Programs\Python\Python38-32\;C:\Users\UserPC\AppData\Local\Microsoft\WindowsApps;C:\Users\UserPC\.dotnet\tools;C:\ProgramData\chocolatey\lib\elasticsearch\tools\elasticsearch-6.7.1\bin;C:\Users\UserPC\AppData\Roaming\npm;C:\Users\UserPC\AppData\Local\Programs\Fiddler
55 verbose lifecycle cognito-email-auth-backend@1.0.0~postinstall: CWD: C:\Users\UserPC\Documents\test-code\amazon-cognito-passwordless-email-auth\cognito
56 silly lifecycle cognito-email-auth-backend@1.0.0~postinstall: Args: [
56 silly lifecycle   '/d /s /c',
56 silly lifecycle   'cd ./lambda-triggers/create-auth-challenge && npm i && cd -'
56 silly lifecycle ]
57 timing audit submit Completed in 372ms
58 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 373ms
59 timing audit body Completed in 1ms
60 silly lifecycle cognito-email-auth-backend@1.0.0~postinstall: Returned: code: 1  signal: null
61 info lifecycle cognito-email-auth-backend@1.0.0~postinstall: Failed to exec postinstall script
62 verbose stack Error: cognito-email-auth-backend@1.0.0 postinstall: `cd ./lambda-triggers/create-auth-challenge && npm i && cd -`
62 verbose stack Exit status 1
62 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
62 verbose stack     at EventEmitter.emit (events.js:315:20)
62 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
62 verbose stack     at ChildProcess.emit (events.js:315:20)
62 verbose stack     at maybeClose (internal/child_process.js:1051:16)
62 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
63 verbose pkgid cognito-email-auth-backend@1.0.0
64 verbose cwd C:\Users\UserPC\Documents\test-code\amazon-cognito-passwordless-email-auth\cognito
65 verbose Windows_NT 10.0.18362
66 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
67 verbose node v14.4.0
68 verbose npm  v6.14.5
69 error code ELIFECYCLE
70 error errno 1
71 error cognito-email-auth-backend@1.0.0 postinstall: `cd ./lambda-triggers/create-auth-challenge && npm i && cd -`
71 error Exit status 1
72 error Failed at the cognito-email-auth-backend@1.0.0 postinstall script.
72 error This is probably not a problem with npm. There is likely additional logging output above.
73 verbose exit [ 1, true ]`

**Comment by hanifasterling** [comment]
[error-file.txt](https://github.com/aws-samples/amazon-cognito-passwordless-email-auth/files/5408056/error-file.txt)

**Comment by ottokruse** [comment]
Looks like Windows issue. Do you mind trying with a Unix-like shell such as sh, bash, zsh, "Linux Subsystem for Windows", Cygwin, Git bash.

**Comment by hanifasterling** [comment]
It works nicely for WSL ... However, for Gitbash - the same issue.
