### ISSUE TITLE
Error: Email address is not verified. The following identities failed the check in region US-EAST-1

### ISSUE THREAD

**Issue by arunned** [aws-samples/amazon-cognito-passwordless-email-auth#8]
Not sure what I am doing wrong. But I keep getting this error message. When I check in Cognito the user is verified and confirmed. Any help is appreciated. 

{
    "errorMessage": "Email address is not verified. The following identities failed the check in region US-EAST-1: xxxxxxxxxxxx@gmail.com",
    "errorType": "MessageRejected",
    "stackTrace": [
        "Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/query.js:47:29)",
        "Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)",
        "Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)",
        "Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)",
        "Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
        "AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "/var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
        "Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)",
        "Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)"
    ]
}

**Comment by ottokruse** [comment]
Hi arunned. You need to also verify that e-mail address in Amazon SES, as it seems you are still in the SES sandbox. See here: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/verify-email-addresses-procedure.html

**Comment by arunned** [comment]
got it thanks. Will check it now. I knew i was missing something.

**Comment by arunned** [comment]
perfect. Worked as expected.. Thanks for the quick response.

**Comment by kazinayem2011** [comment]
I'm also facing the same issue. As per the answer from @ottokruse what actually SES Sandbox does? Do i have to store all the registered email in SES and have to verify email before getting registered? Please help me.

**Comment by ottokruse** [comment]
Have a read of the prerequisite, it contains links to docs explaining all about the sandbox and such: https://github.com/aws-samples/amazon-cognito-passwordless-email-auth/tree/master/cognito#pre-requisite

Short answer: no you do not need to register mails individually in SES - but you need to verify the domain
